<a href="https://colab.research.google.com/github/monirsk/TensorFlow_Thesis/blob/main/tensorflow1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor is an N-dimensional array of data

In [5]:
import tensorflow as tf

In [ ]:
#Initialing of tensors

x = tf.constant(4)
print(x)

y = tf.constant([1,2,3,4])
print(y, type(y))

z = tf.constant([[1,2,3],[4,5,6]])
print(z, type(z))


tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
z = tf.range(8)
print(z)

tf.Tensor([0 1 2 3 4 5 6 7], shape=(8,), dtype=int32)


In [ ]:
sum =0
for x in z:
    sum+=x
print(sum)

if sum==tf.reduce_sum(z):
    print("True")
else:
    print("False")


tf.Tensor(28, shape=(), dtype=int32)
True


In [ ]:
c = tf.range(1,10)
print(c)

c2 = tf.range(2,20,3)
print(c2)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor([ 2  5  8 11 14 17], shape=(6,), dtype=int32)


# Basic Operations of tensors (add, sub, mul)

In [ ]:
x1 = tf.constant([10,20,30])
x2 = tf.constant([11,22,33])

x3 = tf.add(x1,x2) # x3 = x1+x2 is also correct
print(x3)

x3 = tf.subtract(x1,x2)
print(x3)

tf.Tensor([21 42 63], shape=(3,), dtype=int32)
tf.Tensor([-1 -2 -3], shape=(3,), dtype=int32)


#Slicing works similar as in the normal python array

In [ ]:
f1 = tf.constant([1,2,3, 30])

print(f1[:])
print(f1[1:2])
print(f1[1:])
print(f1[:2])
print(f1[::-1])


tf.Tensor([ 1  2  3 30], shape=(4,), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor([ 2  3 30], shape=(3,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([30  3  2  1], shape=(4,), dtype=int32)


In [7]:
f2 = tf.constant([[1,2,3,4],
      [4,5,5,7],
      [4,5,6,6]])

print(f2[0])  # Prints the first row
print(f2[0][0]) # Prints the first element of the first row
print(f2[0:2]) # Prints the first two rows

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(
[[1 2 3 4]
 [4 5 5 7]], shape=(2, 4), dtype=int32)


In [11]:
f2 = tf.constant([[1,2,3,4],
                  [4,5,5,7],
                  [4,5,6,6]])

firts_column = f2[:,0]
print(firts_column)

second_row = f2[1,:] # Second row same as f2[1]
print(second_row)


print(f2[:2,0]) # First column of 1st and 2nd row

tf.Tensor([1 4 4], shape=(3,), dtype=int32)
tf.Tensor([4 5 5 7], shape=(4,), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)
